export const apps = [
  {
    image: "/assets/demo-app (1).webp",
    title: "ChatSphere",
    companyName: "NeuraSoft Ltd.",
    id: 1,
    description:
      "A modern chat app with end-to-end encryption and group video calls.",
    size: 85,
    reviews: 2400,
    ratingAvg: 4.6,
    downloads: 1500000,
    ratings: [
      { name: "1 star", count: 120 },
      { name: "2 star", count: 180 },
      { name: "3 star", count: 400 },
      { name: "4 star", count: 620 },
      { name: "5 star", count: 1080 },
    ],
  },
  {
    image: "/assets/demo-app (2).webp",
    title: "TaskFlow",
    companyName: "BrightPixel Studios",
    id: 2,
    description:
      "Organize your projects and daily to-dos with smart AI recommendations.",
    size: 42,
    reviews: 1100,
    ratingAvg: 4.3,
    downloads: 680000,
    ratings: [
      { name: "1 star", count: 70 },
      { name: "2 star", count: 100 },
      { name: "3 star", count: 210 },
      { name: "4 star", count: 350 },
      { name: "5 star", count: 370 },
    ],
  },
  {
    image: "/assets/demo-app (3).webp",
    title: "FitTrack",
    companyName: "CoreMotion Inc.",
    id: 3,
    description:
      "Track workouts, calories, and progress with personalized plans.",
    size: 95,
    reviews: 5600,
    ratingAvg: 4.8,
    downloads: 5200000,
    ratings: [
      { name: "1 star", count: 300 },
      { name: "2 star", count: 220 },
      { name: "3 star", count: 480 },
      { name: "4 star", count: 1200 },
      { name: "5 star", count: 3400 },
    ],
  },
  {
    image: "/assets/demo-app (4).webp",
    title: "NoteVerse",
    companyName: "ZenApps Co.",
    id: 4,
    description:
      "Sync your notes across devices with markdown and audio support.",
    size: 28,
    reviews: 3000,
    ratingAvg: 4.4,
    downloads: 900000,
    ratings: [
      { name: "1 star", count: 130 },
      { name: "2 star", count: 160 },
      { name: "3 star", count: 400 },
      { name: "4 star", count: 900 },
      { name: "5 star", count: 1410 },
    ],
  },
  {
    image: "/assets/demo-app (5).webp",
    title: "SnapTune",
    companyName: "LyricWorks",
    id: 5,
    description:
      "Discover new music and auto-sync lyrics for your favorite songs.",
    size: 67,
    reviews: 4700,
    ratingAvg: 4.7,
    downloads: 3100000,
    ratings: [
      { name: "1 star", count: 210 },
      { name: "2 star", count: 300 },
      { name: "3 star", count: 550 },
      { name: "4 star", count: 1100 },
      { name: "5 star", count: 2540 },
    ],
  },
  {
    image: "/assets/demo-app (6).webp",
    title: "MindEase",
    companyName: "CalmSpace Labs",
    id: 6,
    description: "Meditation and stress-relief sessions tailored to your mood.",
    size: 60,
    reviews: 3200,
    ratingAvg: 4.5,
    downloads: 2100000,
    ratings: [
      { name: "1 star", count: 190 },
      { name: "2 star", count: 250 },
      { name: "3 star", count: 480 },
      { name: "4 star", count: 900 },
      { name: "5 star", count: 1380 },
    ],
  },
  {
    image: "/assets/demo-app (1).webp",
    title: "RecipeGo",
    companyName: "FoodVerse",
    id: 7,
    description:
      "Discover quick recipes and generate shopping lists instantly.",
    size: 51,
    reviews: 2700,
    ratingAvg: 4.2,
    downloads: 890000,
    ratings: [
      { name: "1 star", count: 150 },
      { name: "2 star", count: 240 },
      { name: "3 star", count: 600 },
      { name: "4 star", count: 870 },
      { name: "5 star", count: 840 },
    ],
  },
  {
    image: "/assets/demo-app (1).webp",
    title: "Budgetify",
    companyName: "FinEdge Systems",
    id: 8,
    description:
      "Track your spending, set budgets, and save smarter with AI insights.",
    size: 39,
    reviews: 3800,
    ratingAvg: 4.6,
    downloads: 1300000,
    ratings: [
      { name: "1 star", count: 180 },
      { name: "2 star", count: 200 },
      { name: "3 star", count: 450 },
      { name: "4 star", count: 1000 },
      { name: "5 star", count: 1970 },
    ],
  },
  {
    image: "/assets/demo-app (5).webp",
    title: "TravelMate",
    companyName: "SkyLoop Global",
    id: 9,
    description:
      "Plan trips, book hotels, and explore hidden destinations worldwide.",
    size: 112,
    reviews: 4900,
    ratingAvg: 4.7,
    downloads: 4600000,
    ratings: [
      { name: "1 star", count: 260 },
      { name: "2 star", count: 300 },
      { name: "3 star", count: 500 },
      { name: "4 star", count: 1000 },
      { name: "5 star", count: 2840 },
    ],
  },
  {
    image: "/assets/demo-app (3).webp",
    title: "ShopSmart",
    companyName: "RetailEdge",
    id: 10,
    description:
      "Compare prices, get cashback, and track online deals in one place.",
    size: 70,
    reviews: 5200,
    ratingAvg: 4.5,
    downloads: 5700000,
    ratings: [
      { name: "1 star", count: 300 },
      { name: "2 star", count: 400 },
      { name: "3 star", count: 800 },
      { name: "4 star", count: 1300 },
      { name: "5 star", count: 2700 },
    ],
  },
  {
    image: "/assets/demo-app (1).webp",
    title: "EduQuest",
    companyName: "Learnova",
    id: 11,
    description:
      "Interactive courses and skill paths with AI tutoring support.",
    size: 82,
    reviews: 3500,
    ratingAvg: 4.3,
    downloads: 2100000,
    ratings: [
      { name: "1 star", count: 200 },
      { name: "2 star", count: 280 },
      { name: "3 star", count: 600 },
      { name: "4 star", count: 950 },
      { name: "5 star", count: 1470 },
    ],
  },
  {
    image: "/assets/demo-app (4).webp",
    title: "GameBoost",
    companyName: "Velocity Interactive",
    id: 12,
    description:
      "Boost performance and reduce lag in your favorite mobile games.",
    size: 56,
    reviews: 6400,
    ratingAvg: 4.1,
    downloads: 4800000,
    ratings: [
      { name: "1 star", count: 400 },
      { name: "2 star", count: 620 },
      { name: "3 star", count: 1200 },
      { name: "4 star", count: 1800 },
      { name: "5 star", count: 2380 },
    ],
  },
  {
    image: "/assets/demo-app (2).webp",
    title: "PhotoBlend",
    companyName: "PixelForge Labs",
    id: 13,
    description:
      "AI-powered photo editor with blending modes and smart filters.",
    size: 88,
    reviews: 5500,
    ratingAvg: 4.6,
    downloads: 3400000,
    ratings: [
      { name: "1 star", count: 200 },
      { name: "2 star", count: 260 },
      { name: "3 star", count: 640 },
      { name: "4 star", count: 1200 },
      { name: "5 star", count: 3200 },
    ],
  },
  {
    image: "/assets/demo-app (5).webp",
    title: "StreamSync",
    companyName: "VidX Media",
    id: 14,
    description: "Watch live shows and sync streaming across multiple devices.",
    size: 110,
    reviews: 4700,
    ratingAvg: 4.4,
    downloads: 4200000,
    ratings: [
      { name: "1 star", count: 280 },
      { name: "2 star", count: 330 },
      { name: "3 star", count: 580 },
      { name: "4 star", count: 1000 },
      { name: "5 star", count: 2510 },
    ],
  },
  {
    image: "/assets/demo-app (4).webp",
    title: "CryptoLens",
    companyName: "BlockSphere",
    id: 15,
    description:
      "Track crypto prices, set alerts, and get insights in real time.",
    size: 53,
    reviews: 4300,
    ratingAvg: 4.2,
    downloads: 2700000,
    ratings: [
      { name: "1 star", count: 230 },
      { name: "2 star", count: 320 },
      { name: "3 star", count: 700 },
      { name: "4 star", count: 1100 },
      { name: "5 star", count: 1950 },
    ],
  },
  {
    image: "/assets/demo-app (3).webp",
    title: "SleepWave",
    companyName: "DreamSync",
    id: 16,
    description: "Sleep tracker with smart alarm and soundscape generation.",
    size: 47,
    reviews: 2500,
    ratingAvg: 4.5,
    downloads: 1200000,
    ratings: [
      { name: "1 star", count: 100 },
      { name: "2 star", count: 150 },
      { name: "3 star", count: 320 },
      { name: "4 star", count: 700 },
      { name: "5 star", count: 1230 },
    ],
  },
  {
    image: "/assets/demo-app (3).webp",
    title: "Weatherly",
    companyName: "Nimbus Co.",
    id: 17,
    description:
      "Beautiful weather forecasts with real-time radar and widgets.",
    size: 34,
    reviews: 5100,
    ratingAvg: 4.7,
    downloads: 4300000,
    ratings: [
      { name: "1 star", count: 210 },
      { name: "2 star", count: 240 },
      { name: "3 star", count: 480 },
      { name: "4 star", count: 900 },
      { name: "5 star", count: 3270 },
    ],
  },
  {
    image: "/assets/demo-app (2).webp",
    title: "VoiceCraft",
    companyName: "EchoLab AI",
    id: 18,
    description:
      "Generate realistic AI voices and clone your own for narration.",
    size: 90,
    reviews: 1800,
    ratingAvg: 4.6,
    downloads: 820000,
    ratings: [
      { name: "1 star", count: 90 },
      { name: "2 star", count: 120 },
      { name: "3 star", count: 200 },
      { name: "4 star", count: 400 },
      { name: "5 star", count: 990 },
    ],
  },
  {
    image: "/assets/demo-app (5).webp",
    title: "SecureVault",
    companyName: "LockBox Systems",
    id: 19,
    description: "Store and encrypt passwords safely with biometric unlock.",
    size: 25,
    reviews: 3900,
    ratingAvg: 4.8,
    downloads: 2600000,
    ratings: [
      { name: "1 star", count: 100 },
      { name: "2 star", count: 130 },
      { name: "3 star", count: 280 },
      { name: "4 star", count: 720 },
      { name: "5 star", count: 2670 },
    ],
  },
  {
    image: "/assets/demo-app (2).webp",
    title: "EventLink",
    companyName: "GatherWorks",
    id: 20,
    description:
      "Find local events, concerts, and meetups tailored to your interests.",
    size: 62,
    reviews: 2900,
    ratingAvg: 4.3,
    downloads: 990000,
    ratings: [
      { name: "1 star", count: 160 },
      { name: "2 star", count: 210 },
      { name: "3 star", count: 480 },
      { name: "4 star", count: 900 },
      { name: "5 star", count: 1150 },
    ],
  },
];
